resources:
  - name: incoming_basic_hook
    type: IncomingWebhook
    configuration:
      webhookName: in_hook_basic
 
  - name: helm_chart_resource
    type: HelmChart
    configuration:
      sourceArtifactory: artifactory_eu
      repository: helm
      chart: spring-petclinic-ci-cd-k8s-chart
      version: ''

pipelines:
  - name: deploy_spring_pet_clinic
    steps:
      - name: start_by_hook
        type: Bash
        configuration:
          inputResources:
            - name: incoming_basic_hook
        execution:
          onExecute:
            - echo "job triggered by resource-> $step_triggered_by_resource_name"
            - echo "$res_incoming_basic_hook_payload" | jq '.' > payload.json
            - echo "$(read_json payload.json my.nested.object)"

      - name: deploy_helm_chart
        type: HelmDeploy
        configuration:
          integrations:
            - name: app_spring_pet_clinic_k8s_cluster_integration
          releaseName: spring-petclinic-ci-cd-k8s-chart
          flags: '--namespace dev'
          valueFilePaths:
            - values.yaml
        execution:
          onStart:
            - helm init --upgrade
