# CI in Pipelines, CD in Jenkins
resources:
  - name: calculate_repository_resource
    type: GitRepo
    configuration:
      gitProvider: talitzgithub  
      path: talitz/spring-petclinic-ci-cd-k8s-example
      branches: 
        include: master
 
  - name: appl_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory_eu
      buildName: build_and_dockerize_spring_pet_clinic
      buildNumber: 1
  
  - name: dbp_image
    type: Image
    configuration:
      registry: artifactory_eu      
      sourceRepository: docker_local  
      imageName: talyi-docker.jfrog.io/pet-clinic
      imageTag: 1.0.0
      autoPull: true      

  - name: spring_files
    type: FileSpec
    configuration:
      sourceArtifactory: artifactory_eu
      pattern: /libs-snapshot-local/org/springframework/samples/spring-petclinic/*.jar
      target: target/      
      buildName: build_and_dockerize_spring_pet_clinic
      limit: 3

pipelines:
  - name: build_and_dockerize_spring_pet_clinic
    steps: 
      - name: build_app
        type: MvnBuild
        configuration:
          affinityGroup: dbp_group
          integrations:
            - name: artifactory_eu
          sourceLocation: .
          autoPublishBuildInfo: true
          mvnCommand: clean install -s settings.xml
          configFileLocation: .
          configFileName: maven.yaml
          inputResources:
            - name: calculate_repository_resource
          outputResources:
            - name: appl_build_info

      - name: docker_build
        type: DockerBuild
        configuration:
          inputSteps:
            - name: build_app          
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: talyi-docker.jfrog.io/pet-clinic
          dockerImageTag: 1.0.${run_number}
          inputResources:
            - name: calculate_repository_resource
            - name: spring_files
          integrations:
            - name: artifactory_eu

      - name: docker_push
        type: DockerPush
        configuration:
          inputSteps:
            - name: docker_build          
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: artifactory_eu
          outputResources:
            - name: dbp_image        

      - name: trigger_jenkins
        type: Jenkins
        configuration:
          inputSteps:
            - name: docker_push
          jenkinsJobName: spring-petclinic-ci-cd-k8s-example
          inputResources:
            - name: dbp_image
          integrations:
            - name: jenkins_server              

# CI in Jenkins, CD in Pipelines
# resources:
#   - name: incoming_basic_hook
#     type: IncomingWebhook
#     configuration:
#       webhookName: in_hook_basic
 
#   - name: spring_helm_chart_resource
#     type: HelmChart
#     configuration:
#       sourceArtifactory: artifactory_eu
#       repository: helm
#       chart: spring-petclinic-ci-cd-k8s-chart
#       version: '1.0.0'

# pipelines:
#   - name: deploy_spring_pet_clinic
#     steps:
#       - name: start_by_hook
#         type: Bash
#         configuration:
#           inputResources:
#             - name: incoming_basic_hook
#         execution:
#           onExecute:
#             - echo "job triggered by resource-> $step_triggered_by_resource_name"
#             - echo "$res_incoming_basic_hook_payload" | jq '.' > payload.json
#             - echo "$(read_json payload.json my.nested.object)"

#       - name: deploy_helm_chart
#         type: HelmDeploy
#         configuration:
#           runtime:
#             type: image
#             image:
#               custom:
#                 name: docker.bintray.io/jfrog/pipelines-u18node
#                 tag: "12.18.2"
#                 autoPull: true
#           integrations:
#             - name: app_spring_pet_clinic_k8s_cluster_integration
#             - name: gcloud_k8s_creds
#           helmVersion: 3
#           lint: true
#           flags: --kube-context=gke_soleng-dev_us-west1-a_artifactory-ha-cluster --set=image.tag=1.0.100
#           inputSteps:
#             - name: start_by_hook
#           inputResources:
#             - name: spring_helm_chart_resource
#           releaseName: spring-petclinic-ci-cd-k8s-example
#           valueFilePaths:
#             - values.yaml
